spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## user service
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
#
#        ## Service2
#        - id: service2
#          uri: lb://service2
#          predicates:
#            - Path=/service2/**
#          filters:
#            - StripPrefix=1
#
#        ## Service2
#        - id: service2
#          uri: lb://service2
#          predicates:
#            - Path=/service2/**
#          filters:
#            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka